service:
  log_level: info
  parsers_file: parsers.conf
  http_server: on
  http_listen: 0.0.0.0
  http_port: 2020

pipeline:
  inputs:
    # https://docs.fluentbit.io/manual/data-pipeline/inputs/tail
    - name: tail
      path: _var/log/containers/*.log
      tag_regex: "(?<file_name>(?<pod_name>[^_]+)_(?<namespace>[^_]+)_(?<container_name>[^_]+)-(?<container_id>[a-f0-9]{64})\\.log)$"
      tag: "kube.var.log.containers.<file_name>"
      buffer_chunk_size: 10MB # Reduces debug-level output, increases throughput slightly
      buffer_max_size: 10MB
      refresh_interval: 2     # seconds. This is set low so the test can detect new log files quickly
      rotate_wait: 5          # seconds. 5 is the default.
      read_from_head: true    # Start reading from the beginning of the file. Needed if the log file is present prior to starting Fluent Bit.
      threaded: true          # Enable multithreading for improved throughput
      exit_on_eof: true
      parser: cri
      processors:
       logs:
        - name: kubernetes
          merge_log: true
          keep_log: false
          merge_parser: logfmt

        # Calculate a checksum to ensure the test is CPU bound
        # The scripts' debug output also give insight into the processing
        - name: lua
          script: checksum_processor.lua
          call: add_checksum

  outputs:
    # https://docs.fluentbit.io/manual/data-pipeline/outputs/file
    - name: file
      match: "*"
      path: fb-output
      file: fb-output.log
      format: out_file
